# Generated by Django 5.2.17 on 2026-08-20 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=150, verbose_name="имя роли"),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("added", "назначена"), ("removed", "снята")],
                        max_length=16,
                        verbose_name="действие",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="когда"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кто изменил",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_changes",
                        to="auth.group",
                        verbose_name="роль",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_changes_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="кому",
                    ),
                ),
            ],
            options={
                "verbose_name": "изменение роли",
                "verbose_name_plural": "изменения ролей",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
