"""Field labels and choice texts switched from Russian to English."""

# Generated by Django 5.2.17 on 2026-09-14 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("panel", "0002_rolechange_target_username"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rolechange",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "role change",
                "verbose_name_plural": "role changes",
            },
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="action",
            field=models.CharField(
                choices=[("added", "granted"), ("removed", "revoked")],
                max_length=16,
                verbose_name="action",
            ),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_changes_made",
                to=settings.AUTH_USER_MODEL,
                verbose_name="changed by",
            ),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, verbose_name="created at"
            ),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_changes",
                to="auth.group",
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="group_name",
            field=models.CharField(max_length=150, verbose_name="role name"),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="target",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_changes_received",
                to=settings.AUTH_USER_MODEL,
                verbose_name="target",
            ),
        ),
        migrations.AlterField(
            model_name="rolechange",
            name="target_username",
            field=models.CharField(max_length=150, verbose_name="target username"),
        ),
    ]
